# SPDX-FileCopyrightText: Copyright (c) 2023 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
docker:
  image: yegor256/rust
assets:
  credentials: yegor256/home#assets/crates-credentials
install: |
  pdd --file=/dev/null
merge:
  script: |
    cargo --color=never test -vv
    cargo --color=never fmt --check
    cargo doc --no-deps
    cargo clippy
release:
  pre: false
  script: |-
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    sed -i -e "s/^version = \"0.0.0\"/version = \"${tag}\"/" Cargo.toml
    sed -i -e "s/0.0.0/${tag}/" src/lib.rs
    cargo --color=never test --all-features -vv -- --nocapture
    cargo --color=never fmt --check
    cargo --color=never clippy -- --no-deps
    git commit -am "${tag}"
    mkdir -p ~/.cargo && cp ../credentials ~/.cargo
    cargo --color=never publish
